services:
  db:
    image: rsanzfloridauni/mi_cine:latest
    container_name: contenedor_mi_cine
    restart: unless-stopped
    ports:
      - "3306:3306"

  php:
    image: rsanzfloridauni/mi_app_cine:latest
    container_name: contenedor_mi_app
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedor_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db